### ISSUE TITLE
Missing 'markup' on Label

### ISSUE THREAD

**Issue by Dunnomix** [ivlevdenis/kivylng#2]
Hello there, i'm sorry if this is not the right spot to post this issue.
I was following a book in wich i'm told to activate markup on a label (so you can use bold, italic, etc)
Here is the snippet i'm working

```
BoxLayout:
    orientation: 'vertical'

    Label:
        font_name: "Roboto"
        markup: True
        text: "[b]00[/b]:00:00"
```

the issue is within the markup keyword, it doesn't get coloured syntax.

again, sorry if this isn't the right place to mention this, i'm new to gith
